services:
    db:
        image: postgres
        container_name: postgres_db_example
        environment:
            POSTGRES_DB: ${APP_CONFIG__DB__DATABASE}
            POSTGRES_USER: ${APP_CONFIG__DB__USER}
            POSTGRES_PASSWORD: ${APP_CONFIG__DB__PASSWORD}
        ports:
            - ${APP_CONFIG__DB__PORT}:5432

    adminer:
        image: adminer
        ports:
            - 8080:8080

    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
            PGADMIN_CONFIG_SERVER_MODE: "False"
        ports:
            - 5050:80
